package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1



/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private int idPersona;
     private Empresa empresa;
     private Persona persona;
     private Usuario usuario;
     private int estaActivo;

    public Administrador() {
    }

    public Administrador(Empresa empresa, Persona persona, Usuario usuario, int estaActivo) {
       this.empresa = empresa;
       this.persona = persona;
       this.usuario = usuario;
       this.estaActivo = estaActivo;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }




}


