package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Integer idCalificacion;
     private Centroeventos centroeventos;
     private Cliente cliente;
     private Ejecutivo ejecutivo;
     private Empresa empresa;
     private Espacio espacio;
     private Habitacion habitacion;
     private Hotel hotel;
     private Sucursal sucursal;
     private String comentario;
     private int cantidadEstrellas;
     private Date fechaComentario;

    public Calificacion() {
    }

	
    public Calificacion(Cliente cliente, String comentario, int cantidadEstrellas, Date fechaComentario) {
        this.cliente = cliente;
        this.comentario = comentario;
        this.cantidadEstrellas = cantidadEstrellas;
        this.fechaComentario = fechaComentario;
    }
    public Calificacion(Centroeventos centroeventos, Cliente cliente, Ejecutivo ejecutivo, Empresa empresa, Espacio espacio, Habitacion habitacion, Hotel hotel, Sucursal sucursal, String comentario, int cantidadEstrellas, Date fechaComentario) {
       this.centroeventos = centroeventos;
       this.cliente = cliente;
       this.ejecutivo = ejecutivo;
       this.empresa = empresa;
       this.espacio = espacio;
       this.habitacion = habitacion;
       this.hotel = hotel;
       this.sucursal = sucursal;
       this.comentario = comentario;
       this.cantidadEstrellas = cantidadEstrellas;
       this.fechaComentario = fechaComentario;
    }
   
    public Integer getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Centroeventos getCentroeventos() {
        return this.centroeventos;
    }
    
    public void setCentroeventos(Centroeventos centroeventos) {
        this.centroeventos = centroeventos;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Espacio getEspacio() {
        return this.espacio;
    }
    
    public void setEspacio(Espacio espacio) {
        this.espacio = espacio;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public int getCantidadEstrellas() {
        return this.cantidadEstrellas;
    }
    
    public void setCantidadEstrellas(int cantidadEstrellas) {
        this.cantidadEstrellas = cantidadEstrellas;
    }
    public Date getFechaComentario() {
        return this.fechaComentario;
    }
    
    public void setFechaComentario(Date fechaComentario) {
        this.fechaComentario = fechaComentario;
    }




}


