package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Centroeventos generated by hbm2java
 */
public class Centroeventos  implements java.io.Serializable {


     private Integer id;
     private Sucursal sucursal;
     private String descripcion;
     private int estaActivo;
     private String rutaImagen;
     private Set calificacions = new HashSet(0);

    public Centroeventos() {
    }

	
    public Centroeventos(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public Centroeventos(Sucursal sucursal, String descripcion, int estaActivo, String rutaImagen, Set calificacions) {
       this.sucursal = sucursal;
       this.descripcion = descripcion;
       this.estaActivo = estaActivo;
       this.rutaImagen = rutaImagen;
       this.calificacions = calificacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public String getRutaImagen() {
        return this.rutaImagen;
    }
    
    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}


