package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idPersona;
     private Persona personaByRutPersona;
     private Persona personaById;
     private Usuario usuario;
     private Integer numeroTarjeta;
     private String sexo;
     private String ciudad;
     private String comuna;
     private String calleNumero;
     private int estaActivo;
     private Set calificacions = new HashSet(0);
     private Set reservacions = new HashSet(0);

    public Cliente() {
    }
    public Cliente(Usuario usuario) {
       this.usuario = usuario;        
    }

	
    public Cliente(Persona personaByRutPersona, Persona personaById, Usuario usuario, int estaActivo) {
        this.personaByRutPersona = personaByRutPersona;
        this.personaById = personaById;
        this.usuario = usuario;
        this.estaActivo = estaActivo;
    }
    public Cliente(Persona personaByRutPersona, Persona personaById, Usuario usuario, Integer numeroTarjeta, String sexo, String ciudad, String comuna, String calleNumero, int estaActivo, Set calificacions, Set reservacions) {
       this.personaByRutPersona = personaByRutPersona;
       this.personaById = personaById;
       this.usuario = usuario;
       this.numeroTarjeta = numeroTarjeta;
       this.sexo = sexo;
       this.ciudad = ciudad;
       this.comuna = comuna;
       this.calleNumero = calleNumero;
       this.estaActivo = estaActivo;
       this.calificacions = calificacions;
       this.reservacions = reservacions;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Persona getPersonaByRutPersona() {
        return this.personaByRutPersona;
    }
    
    public void setPersonaByRutPersona(Persona personaByRutPersona) {
        this.personaByRutPersona = personaByRutPersona;
    }
    public Persona getPersonaById() {
        return this.personaById;
    }
    
    public void setPersonaById(Persona personaById) {
        this.personaById = personaById;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(Integer numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public String getCalleNumero() {
        return this.calleNumero;
    }
    
    public void setCalleNumero(String calleNumero) {
        this.calleNumero = calleNumero;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }




}


