package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String rut;
     private String directorio;
     private int estaActivo;
     private String rutaImagen;
     private Set sucursals = new HashSet(0);
     private Set ejecutivos = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set administradors = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String nombre, String rut, String directorio, int estaActivo) {
        this.nombre = nombre;
        this.rut = rut;
        this.directorio = directorio;
        this.estaActivo = estaActivo;
    }
    public Empresa(String nombre, String rut, String directorio, int estaActivo, String rutaImagen, Set sucursals, Set ejecutivos, Set calificacions, Set administradors) {
       this.nombre = nombre;
       this.rut = rut;
       this.directorio = directorio;
       this.estaActivo = estaActivo;
       this.rutaImagen = rutaImagen;
       this.sucursals = sucursals;
       this.ejecutivos = ejecutivos;
       this.calificacions = calificacions;
       this.administradors = administradors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getDirectorio() {
        return this.directorio;
    }
    
    public void setDirectorio(String directorio) {
        this.directorio = directorio;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public String getRutaImagen() {
        return this.rutaImagen;
    }
    
    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }
    public Set getEjecutivos() {
        return this.ejecutivos;
    }
    
    public void setEjecutivos(Set ejecutivos) {
        this.ejecutivos = ejecutivos;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }




}


