package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Espacio generated by hbm2java
 */
public class Espacio  implements java.io.Serializable {


     private int id;
     private int metrosCuadrados;
     private boolean tienePiscina;
     private int cantMaximaPersonas;
     private int precioHora;
     private boolean tieneEscenario;
     private boolean accesoDiscapacitados;
     private int estaActivo;
     private String rutaImagen;
     private Set calificacions = new HashSet(0);
     private Set reservacions = new HashSet(0);

    public Espacio() {
    }

	
    public Espacio(int id, int metrosCuadrados, boolean tienePiscina, int cantMaximaPersonas, int precioHora, boolean tieneEscenario, boolean accesoDiscapacitados, int estaActivo, String rutaImagen) {
        this.id = id;
        this.metrosCuadrados = metrosCuadrados;
        this.tienePiscina = tienePiscina;
        this.cantMaximaPersonas = cantMaximaPersonas;
        this.precioHora = precioHora;
        this.tieneEscenario = tieneEscenario;
        this.accesoDiscapacitados = accesoDiscapacitados;
        this.estaActivo = estaActivo;
        this.rutaImagen = rutaImagen;
    }
    public Espacio(int id, int metrosCuadrados, boolean tienePiscina, int cantMaximaPersonas, int precioHora, boolean tieneEscenario, boolean accesoDiscapacitados, int estaActivo, String rutaImagen, Set calificacions, Set reservacions) {
       this.id = id;
       this.metrosCuadrados = metrosCuadrados;
       this.tienePiscina = tienePiscina;
       this.cantMaximaPersonas = cantMaximaPersonas;
       this.precioHora = precioHora;
       this.tieneEscenario = tieneEscenario;
       this.accesoDiscapacitados = accesoDiscapacitados;
       this.estaActivo = estaActivo;
       this.rutaImagen = rutaImagen;
       this.calificacions = calificacions;
       this.reservacions = reservacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMetrosCuadrados() {
        return this.metrosCuadrados;
    }
    
    public void setMetrosCuadrados(int metrosCuadrados) {
        this.metrosCuadrados = metrosCuadrados;
    }
    public boolean isTienePiscina() {
        return this.tienePiscina;
    }
    
    public void setTienePiscina(boolean tienePiscina) {
        this.tienePiscina = tienePiscina;
    }
    public int getCantMaximaPersonas() {
        return this.cantMaximaPersonas;
    }
    
    public void setCantMaximaPersonas(int cantMaximaPersonas) {
        this.cantMaximaPersonas = cantMaximaPersonas;
    }
    public int getPrecioHora() {
        return this.precioHora;
    }
    
    public void setPrecioHora(int precioHora) {
        this.precioHora = precioHora;
    }
    public boolean isTieneEscenario() {
        return this.tieneEscenario;
    }
    
    public void setTieneEscenario(boolean tieneEscenario) {
        this.tieneEscenario = tieneEscenario;
    }
    public boolean isAccesoDiscapacitados() {
        return this.accesoDiscapacitados;
    }
    
    public void setAccesoDiscapacitados(boolean accesoDiscapacitados) {
        this.accesoDiscapacitados = accesoDiscapacitados;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public String getRutaImagen() {
        return this.rutaImagen;
    }
    
    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }




}


