package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion implements java.io.Serializable {

    private int numero;
    private int metrosCuadrados;
    private int precioPorDia;
    private int precioPorNoche;
    private int cantidadMaximaPersonas;
    private int estaActivo;
    private String rutaImagen;
    private Set calificacions = new HashSet(0);
    private Set reservacions = new HashSet(0);

    public Habitacion() {
    }

    public Habitacion(int numero) {
        this.numero = numero;
    }
    public Habitacion(int numero, int metrosCuadrados, int precioPorDia, int precioPorNoche, int cantidadMaximaPersonas, int estaActivo, String rutaImagen) {
        this.numero = numero;
        this.metrosCuadrados = metrosCuadrados;
        this.precioPorDia = precioPorDia;
        this.precioPorNoche = precioPorNoche;
        this.cantidadMaximaPersonas = cantidadMaximaPersonas;
        this.estaActivo = estaActivo;
        this.rutaImagen = rutaImagen;
    }

    public Habitacion(int numero, int metrosCuadrados, int precioPorDia, int precioPorNoche, int cantidadMaximaPersonas, int estaActivo, String rutaImagen, Set calificacions, Set reservacions) {
        this.numero = numero;
        this.metrosCuadrados = metrosCuadrados;
        this.precioPorDia = precioPorDia;
        this.precioPorNoche = precioPorNoche;
        this.cantidadMaximaPersonas = cantidadMaximaPersonas;
        this.estaActivo = estaActivo;
        this.rutaImagen = rutaImagen;
        this.calificacions = calificacions;
        this.reservacions = reservacions;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public int getMetrosCuadrados() {
        return this.metrosCuadrados;
    }

    public void setMetrosCuadrados(int metrosCuadrados) {
        this.metrosCuadrados = metrosCuadrados;
    }

    public int getPrecioPorDia() {
        return this.precioPorDia;
    }

    public void setPrecioPorDia(int precioPorDia) {
        this.precioPorDia = precioPorDia;
    }

    public int getPrecioPorNoche() {
        return this.precioPorNoche;
    }

    public void setPrecioPorNoche(int precioPorNoche) {
        this.precioPorNoche = precioPorNoche;
    }

    public int getCantidadMaximaPersonas() {
        return this.cantidadMaximaPersonas;
    }

    public void setCantidadMaximaPersonas(int cantidadMaximaPersonas) {
        this.cantidadMaximaPersonas = cantidadMaximaPersonas;
    }

    public int getEstaActivo() {
        return this.estaActivo;
    }

    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }

    public String getRutaImagen() {
        return this.rutaImagen;
    }

    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }

    public Set getCalificacions() {
        return this.calificacions;
    }

    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }

    public Set getReservacions() {
        return this.reservacions;
    }

    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }

}
