package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer id;
     private Sucursal sucursal;
     private Integer cantidadEstrellas;
     private int estaActivo;
     private Set calificacions = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(Sucursal sucursal, int estaActivo) {
        this.sucursal = sucursal;
        this.estaActivo = estaActivo;
    }
    public Hotel(Sucursal sucursal, Integer cantidadEstrellas, int estaActivo, Set calificacions) {
       this.sucursal = sucursal;
       this.cantidadEstrellas = cantidadEstrellas;
       this.estaActivo = estaActivo;
       this.calificacions = calificacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Integer getCantidadEstrellas() {
        return this.cantidadEstrellas;
    }
    
    public void setCantidadEstrellas(Integer cantidadEstrellas) {
        this.cantidadEstrellas = cantidadEstrellas;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}


