package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String rut;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private int telefono;
     private String correo;
     private int estaActivo;
     private Set clientesForRutPersona = new HashSet(0);
     private Cliente clienteById;
     private Ejecutivo ejecutivo;
     private Administrador administrador;

    public Persona() {
    }

	
    public Persona(String rut, String nombre, String apellido, Date fechaNacimiento, int telefono, String correo, int estaActivo) {
        this.rut = rut;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.telefono = telefono;
        this.correo = correo;
        this.estaActivo = estaActivo;
    }
    public Persona(String rut, String nombre, String apellido, Date fechaNacimiento, int telefono, String correo, int estaActivo, Set clientesForRutPersona, Cliente clienteById, Ejecutivo ejecutivo, Administrador administrador) {
       this.rut = rut;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.correo = correo;
       this.estaActivo = estaActivo;
       this.clientesForRutPersona = clientesForRutPersona;
       this.clienteById = clienteById;
       this.ejecutivo = ejecutivo;
       this.administrador = administrador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getEstaActivo() {
        return this.estaActivo;
    }
    
    public void setEstaActivo(int estaActivo) {
        this.estaActivo = estaActivo;
    }
    public Set getClientesForRutPersona() {
        return this.clientesForRutPersona;
    }
    
    public void setClientesForRutPersona(Set clientesForRutPersona) {
        this.clientesForRutPersona = clientesForRutPersona;
    }
    public Cliente getClienteById() {
        return this.clienteById;
    }
    
    public void setClienteById(Cliente clienteById) {
        this.clienteById = clienteById;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }




}


