package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private Integer idReservacion;
     private Cliente cliente;
     private Ejecutivo ejecutivo;
     private Espacio espacio;
     private Habitacion habitacion;
     private Date fechaReserva;
     private Date horaReserva;
     private Integer horasReservadas;
     private boolean estaAprobada;
     private int precioTotal;
     private boolean estaPagado;
     private String estado;

    public Reservacion() {
    }

	
    public Reservacion(Cliente cliente, boolean estaAprobada, int precioTotal, boolean estaPagado, String estado) {
        this.cliente = cliente;
        this.estaAprobada = estaAprobada;
        this.precioTotal = precioTotal;
        this.estaPagado = estaPagado;
        this.estado = estado;
    }
    public Reservacion(Cliente cliente, Ejecutivo ejecutivo, Espacio espacio, Habitacion habitacion, Date fechaReserva, Date horaReserva, Integer horasReservadas, boolean estaAprobada, int precioTotal, boolean estaPagado, String estado) {
       this.cliente = cliente;
       this.ejecutivo = ejecutivo;
       this.espacio = espacio;
       this.habitacion = habitacion;
       this.fechaReserva = fechaReserva;
       this.horaReserva = horaReserva;
       this.horasReservadas = horasReservadas;
       this.estaAprobada = estaAprobada;
       this.precioTotal = precioTotal;
       this.estaPagado = estaPagado;
       this.estado = estado;
    }
    
    public Reservacion(Cliente cliente, Habitacion habitacion,int precioTotal, String estado) {
       this.cliente = cliente;
       this.habitacion = habitacion;
       this.precioTotal = precioTotal;
       this.estado = estado;
    }
   
    public Integer getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(Integer idReservacion) {
        this.idReservacion = idReservacion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public Espacio getEspacio() {
        return this.espacio;
    }
    
    public void setEspacio(Espacio espacio) {
        this.espacio = espacio;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Date getFechaReserva() {
        return this.fechaReserva;
    }
    
    public void setFechaReserva(Date fechaReserva) {
        this.fechaReserva = fechaReserva;
    }
    public Date getHoraReserva() {
        return this.horaReserva;
    }
    
    public void setHoraReserva(Date horaReserva) {
        this.horaReserva = horaReserva;
    }
    public Integer getHorasReservadas() {
        return this.horasReservadas;
    }
    
    public void setHorasReservadas(Integer horasReservadas) {
        this.horasReservadas = horasReservadas;
    }
    public boolean isEstaAprobada() {
        return this.estaAprobada;
    }
    
    public void setEstaAprobada(boolean estaAprobada) {
        this.estaAprobada = estaAprobada;
    }
    public int getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(int precioTotal) {
        this.precioTotal = precioTotal;
    }
    public boolean isEstaPagado() {
        return this.estaPagado;
    }
    
    public void setEstaPagado(boolean estaPagado) {
        this.estaPagado = estaPagado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


