package Entity;
// Generated 29-11-2016 13:51:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String username;
     private String password;
     private String estado;
     private Set ejecutivos = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set administradors = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String username, String password) {
        this.username = username;
        this.password = password;
        this.estado = "activo";
    }
    
    public Usuario(String username, String password, String estado) {
        this.username = username;
        this.password = password;
        this.estado = estado;
    }
	
    public Usuario(String username, String password, String estado, Set ejecutivos, Set clientes, Set administradors) {
       this.username = username;
       this.password = password;
       this.estado = estado;
       this.ejecutivos = ejecutivos;
       this.clientes = clientes;
       this.administradors = administradors;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEjecutivos() {
        return this.ejecutivos;
    }
    
    public void setEjecutivos(Set ejecutivos) {
        this.ejecutivos = ejecutivos;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }




}


